### ISSUE TITLE
Banyak Bab yg belum di cover

### ISSUE THREAD

**Issue by ekarudianto** [junwatu/pengenalan-nodejs-gitbook#1]
lg keasikan baca bukunya di gitbook tapi ternyata banyak bab yg masih kosong yang cuman ada

```
TODO
```

ayo om rampungin biar ane bisa baca :D

**Comment by junwatu** [comment]
@ekarudianto sorry...masih dalam progress. mungkin update minim sekali seminggu. trims sudah membaca :+1:  :smile_cat:
